version: '3.9'

services:
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: blog_voyage
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - dev
    volumes:
      - ./mysql:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - dev
  
  php:
    build: ./back
    container_name: php_app
    depends_on:
      - database
      - phpmyadmin
    networks:
      - dev
    volumes:
      - .:/var/www/
    ports:
      - "8000:8000"

  react:
    build: ./client
    container_name: react_app
    networks:
      - dev
    ports:
      - "3000:3000"
    depends_on:
      - php
    volumes:
     - ./client:/var/www/client
     - ./client/node_modules:/var/www/client/node_modules
    

networks:
  dev:
    driver: bridge
volumes:
  database: